version: '3.8'

services:

  mongo:
    image: mongo:4.4.21
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    command: --bind_ip_all
    volumes:
      - ${MONGO_DATA}:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo

# https://github.com/UnusualAlpha/ib-gateway-docker
# ports are only exposed to the docker host (127.0.0.1), but not to the network of the host
# To expose it to the whole network change the port mappings on accordingly (remove the '127.0.0.1:')
#      - "127.0.0.1:4001:4001"
#      - "127.0.0.1:4002:4002"
#      - "127.0.0.1:5901:5900"
# vnc port 5901
  ib-gateway:
    image: ghcr.io/unusualalpha/ib-gateway:latest
    restart: always
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      READ_ONLY_API: ${READ_ONLY_API}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5901:5900"
